#!/bin/bash -e

INCLUDES=$(cat .syntastic_cpp_config)
EXCLUDE_CHECKS="-misc-unused-parameters,-llvm-header-guard,-cppcoreguidelines-pro-type-reinterpret-cast,-modernize-make-unique"

PYLINT="pylint -s n --rcfile $(git rev-parse --show-toplevel)/.pylintrc"
MYPY="mypy --strict"

export MYPYPATH=stubs/

check_file_clang() {
  file="${1}"
  # TODO: add -quiet as soon as it is supported
  clang-tidy --checks=*,${EXCLUDE_CHECKS} \
    --warnings-as-errors=*,${EXCLUDE_CHECKS} ${1} \
    -- -std=c++11 ${INCLUDES}
}

case "${1}" in
  --about )
    echo "Runs a linter on source files"
    ;;
  * )
    for file in `git diff-index --cached --name-only HEAD` ; do
      if [ -f ${file} ]
      then
        if [ ${file: -3} == '.cc' ]
        then
          check_file_clang "${file}"
        fi
        if [ ${file: -4} == '.hpp' ]
        then
          check_file_clang "${file}"
        fi
      fi
    done
    PY_FILES=$(find . -path ./test_task -prune -o -name '*.py' -print)
    $PYLINT $PY_FILES
    $MYPY $PY_FILES
    ;;
esac
