#!/bin/bash -e

INCLUDES="-Icpp -Ithird_party $(pkgconf --cflags python3) -Ibuild"
EXCLUDE_CHECKS="-fuchsia-multiple-inheritance,-fuchsia-overloaded-operator,-fuchsia-default-arguments,-hicpp-braces-around-statements,-readability-braces-around-statements,-llvm-header-guard,-llvm-include-order,-bugprone-suspicious-semicolon"

check_file_clang() {
  file="${1}"
  echo "====> clang-tiding $file"
  # TODO: add -quiet as soon as it is supported
  clang-tidy --checks=*,${EXCLUDE_CHECKS} \
    --warnings-as-errors=*,${EXCLUDE_CHECKS} ${1} \
    -- -std=c++14 ${INCLUDES}
}

for file in $@; do
    check_file_clang "$file"
done
