# Sandbox test utils.
package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "return_arg1",
    srcs = ["return_arg1.cpp"],
)

cc_binary(
    name = "signal_arg1",
    srcs = ["signal_arg1.cpp"],
)

cc_binary(
    name = "wait_arg1",
    srcs = ["wait_arg1.cpp"],
)

cc_binary(
    name = "busywait_arg1",
    srcs = ["busywait_arg1.cpp"],
)

cc_binary(
    name = "malloc_arg1",
    srcs = ["malloc_arg1.cpp"],
)
