# Protobufs for communication
package(default_visibility = ["//visibility:public"])

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
    name = "sha256_cc",
    protos = ["sha256.proto"],
)
