package(default_visibility = ["//visibility:public"])

py_runtime(
    name = "python_3_6",
    files = [
        "python_gateway.sh",
        "@python_repo//:python_3_6_interpreter",
    ],
    interpreter = "python_gateway.sh",
    visibility = ["//visibility:public"],
)
